"""General settings and simulation limits for Phase 3 virtual sensors."""

DEVICE_ID = "bike_001"
DEFAULT_SESSION_ID = "session_001"
DEFAULT_SAMPLE_INTERVAL_SECONDS = 1
DEFAULT_RANDOM_SEED = None

MIN_SPEED_KMH = 0
MAX_SPEED_KMH = 35

MIN_CADENCE_RPM = 0
MAX_CADENCE_RPM = 120

MIN_HEART_RATE_BPM = 70
MAX_HEART_RATE_BPM = 190

MIN_TEMPERATURE_C = 18
MAX_TEMPERATURE_C = 40

MIN_DISTANCE_M = 0.2
MAX_DISTANCE_M = 4.0

